#cloud-config
package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - git
  - postgresql-client

write_files:
  - path: /opt/messenger/docker-compose.yml
    permissions: '0644'
    content: |
      version: '3.8'
      services:
        postgres:
          image: postgres:15-alpine
          container_name: messenger-postgres
          environment:
            POSTGRES_USER: messenger
            POSTGRES_DB: messenger
          env_file:
            - .env
          volumes:
            - postgres_data:/var/lib/postgresql/data
            - /opt/messenger/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
          ports:
            - "127.0.0.1:5432:5432"
          healthcheck:
            test: ["CMD-SHELL", "pg_isready -U messenger"]
            interval: 5s
            timeout: 5s
            retries: 5
          networks:
            - messenger-network
        app:
          image: ${docker_image}
          container_name: messenger-app
          env_file:
            - .env
          ports:
            - "8080:8080"
          depends_on:
            postgres:
              condition: service_healthy
          networks:
            - messenger-network
          restart: unless-stopped
      volumes:
        postgres_data:
      networks:
        messenger-network:
          driver: bridge

  - path: /opt/messenger/init.sql
    permissions: '0644'
    content: |
      CREATE EXTENSION IF NOT EXISTS "pgcrypto";
      CREATE TABLE IF NOT EXISTS users (
          id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          username VARCHAR(50) UNIQUE NOT NULL,
          password_hash VARCHAR(255) NOT NULL,
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );
      CREATE INDEX idx_users_username ON users(username);
      CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username_lower ON users(LOWER(username));
      CREATE TABLE IF NOT EXISTS messages (
          id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
          sender_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          receiver_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          payload BYTEA NOT NULL,
          created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
      );
      CREATE INDEX idx_messages_sender ON messages(sender_id);
      CREATE INDEX idx_messages_receiver ON messages(receiver_id);
      CREATE INDEX idx_messages_created ON messages(created_at DESC);

  - path: /opt/messenger/start.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      cd /opt/messenger
      docker compose down 2>/dev/null || true
      docker compose pull app
      docker compose up -d

runcmd:
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  - chmod a+r /etc/apt/keyrings/docker.gpg
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" > /etc/apt/sources.list.d/docker.list
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  - systemctl start docker
  - systemctl enable docker
  - usermod -aG docker ubuntu
  - mkdir -p /opt/messenger
  - |
    JWT_SECRET=$(echo '${jwt_secret_b64}' | base64 -d)
    DB_PASSWORD=$(echo '${db_password_b64}' | base64 -d)
    DEFAULT_USER=$(echo '${default_user_b64}' | base64 -d)
    DEFAULT_PASSWORD=$(echo '${default_password_b64}' | base64 -d)
    echo "HTTP_ADDR=:8080" > /opt/messenger/.env
    echo "JWT_SECRET=$JWT_SECRET" >> /opt/messenger/.env
    echo "JWT_DURATION=${jwt_duration}" >> /opt/messenger/.env
    echo "DB_HOST=postgres" >> /opt/messenger/.env
    echo "DB_PORT=5432" >> /opt/messenger/.env
    echo "DB_USER=messenger" >> /opt/messenger/.env
    echo "DB_PASSWORD=$DB_PASSWORD" >> /opt/messenger/.env
    echo "DB_NAME=messenger" >> /opt/messenger/.env
    echo "DB_SSLMODE=disable" >> /opt/messenger/.env
    echo "POSTGRES_PASSWORD=$DB_PASSWORD" >> /opt/messenger/.env
    echo "DEFAULT_USER=$DEFAULT_USER" >> /opt/messenger/.env
    echo "DEFAULT_PASSWORD=$DEFAULT_PASSWORD" >> /opt/messenger/.env
  - chmod 600 /opt/messenger/.env
  - chmod +x /opt/messenger/start.sh
  - echo "@reboot root /opt/messenger/start.sh >> /var/log/messenger-startup.log 2>&1" > /etc/cron.d/messenger
  - chmod 644 /etc/cron.d/messenger
  - /opt/messenger/start.sh
  - sleep 30
  - docker compose -f /opt/messenger/docker-compose.yml logs
