#cloud-config
package_update: true
package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release
  - git

write_files:
  - path: /opt/messenger/start.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      set -e
      
      # Decode environment variables
      JWT_SECRET=$(echo '${jwt_secret_b64}' | base64 -d)
      DB_PASSWORD=$(echo '${db_password_b64}' | base64 -d)
      DEFAULT_USER=$(echo '${default_user_b64}' | base64 -d)
      DEFAULT_PASSWORD=$(echo '${default_password_b64}' | base64 -d)
      
      # Create environment file
      cat > /opt/messenger/.env << EOF
      HTTP_ADDR=${http_addr}
      JWT_SECRET=$JWT_SECRET
      JWT_DURATION=${jwt_duration}
      DB_HOST=${db_host}
      DB_PORT=${db_port}
      DB_USER=${db_user}
      DB_PASSWORD=$DB_PASSWORD
      DB_NAME=${db_name}
      DB_SSLMODE=${db_sslmode}
      DEFAULT_USER=$DEFAULT_USER
      DEFAULT_PASSWORD=$DEFAULT_PASSWORD
      EOF
      
      chmod 600 /opt/messenger/.env
      
      # Pull and run application container
      docker pull ${docker_image}
      docker stop ${container_name} 2>/dev/null || true
      docker rm ${container_name} 2>/dev/null || true
      docker run -d \
        --name ${container_name} \
        --restart unless-stopped \
        -p ${app_port}:${app_port} \
        --env-file /opt/messenger/.env \
        ${docker_image}
      
      echo "Application started at $(date)"

runcmd:
  - mkdir -p /opt/messenger
  - chmod +x /opt/messenger/start.sh
  - /opt/messenger/start.sh
  - echo "@reboot root /opt/messenger/start.sh >> /var/log/messenger-startup.log 2>&1" > /etc/cron.d/messenger
  - chmod 644 /etc/cron.d/messenger
